from common import *
import traceback
start=time.monotonic();proto=json.loads((R/'protocol.json').read_text());d=loadrows(R/'inputs/frozen_rows.csv');e=Engine(d);base=joblib.load(R/'models/baseline.joblib');cal=d.index[(d.split=='calibration')&(d.label==0)].to_numpy();se=d.index[d.split=='selection'].to_numpy();br,bm=evaluated(e.predict(base,se),base['threshold']);errors=pd.read_csv(R/'tables/selection_error_conditions.csv');fn_fb=int(errors[errors.condition=='fallback'].FN.iloc[0]);A=pd.read_csv(R/'threshold_sweep.csv');a_best=pick(A.to_dict('records'));blocks=json.loads((R/'manifests/diagnostic_blocks.json').read_text());rows=[];brows=[];routeaudit=[];fitrows=[]
reason=dict(created=pd.Timestamp.now(tz='UTC').isoformat(),A_primary_eligible=int(A.primary_eligible.sum()),selection_baseline_FN=bm['FN'],fallback_FN=fn_fb,decision='execute narrow warmup complement' if fn_fb else 'skip: no development evidence',hypotheses=1,windows=[3,5],normal_train_min=100,normal_calibration_native_min=100,routed_calibration_min=10,small_sample_note='only17/15 routed calibration rows; use all normal available same-length windows for Q95, not route quantile; global mixed-system threshold recalibrated',score_alignment='short-window Q / Q95 from all native normal calibration; original W20 and P0 references unchanged',fallback_if_insufficient='retain entire original system; candidate marked reverted',routing='short w only where originalW20 unavailable and w same-partition past rows available; all other rows exactly original; no burst resets changed',rejection='no configuration meets strict Recall/F2/F1/FP eligibility, or gains fully explained by A threshold-only candidate',new_candidate_budget=24,postprocessing='none',test_sensor_or_error_use=False)
js(R/'B_hypothesis_lock.json',reason)
with (R/'hypotheses.md').open('a') as f:f.write(f'''\n## B 가설 1 — W20 준비 전 P0의 한계만 보완\n\nA 적격 후보는0개이며 개발FN{bm['FN']}개 중{fn_fb}개가 기존P0 구간이다. 3행 또는5행 통계를 쓸 수 있을 때 그 구간만 같은15특징·2성분·Q의 짧은PCA로 보완한다. W20 사용 가능한 행과 모든 버스트 초기화 규칙은 바꾸지 않는다. 이전 실패한 모든버스트1→3→5→10→20라우팅과 범위가 다르다.\n\n정상fit100창, 정상calibration동일길이전체100창, 실제전환경로calibration10행이 최소다. 미달이면 기존모델 그대로 돌아간다. 정상calibration전체 동일길이Q95로 스케일을 정하고 혼합된 운영점수의12목표분위수를 다시 계산한다. 라우팅표본이15/17개로 적어 특정route의 꼬리FPR 추정이 안정적이라는 주장은 하지 않는다.\n\n3/5행두구성×12임계값=24개, A와합계36개다. 전체행 비교와 W20 공통행 비교를 둘다 남긴다. 모든판정은현재까지의행수만 사용하고 미래길이·라벨을사용하지않는다. A의F2최고운영점({a_best['candidate']}, 적격여부와 별도)도 대조한다.\n''')
if fn_fb:
 for w in [3,5]:
  tic=time.perf_counter();name=f'warmup_W{w}';system=dict(base,name=name,entries=dict(base['entries']),short_window=w)
  try:
   tr=d.index[(d.split=='train')&(e.starts_for(w)>=0)].to_numpy();cn=cal[e.starts_for(w)[cal]>=0];routed=cal[(e.starts_for(20)[cal]<0)&(e.starts_for(w)[cal]>=0)];active=len(tr)>=100 and len(cn)>=100 and len(routed)>=10
   routeaudit.append(dict(system=name,normal_train_n=len(tr),normal_calibration_native_n=len(cn),routed_normal_calibration_n=len(routed),active=active,sparse_action='keep original system',calibration_reference_scope='all native normal calibration'))
   if active:
    assert not d.loc[tr,'label'].any();b=fit_pca(e.x(w,tr),2,FEATURES);assert b['q_valid'];ref=reference(score(b,e.x(w,cn))['Q']);system['entries'][w]=dict(bundle=b,reference=ref,train_ids=d.loc[tr,'row_id'].tolist(),normal_calibration_ids=d.loc[cn,'row_id'].tolist());fitrows.extend(dict(model=name,row_id=d.loc[i,'row_id'],role='normal_train') for i in tr)
   else:system=dict(base,name=name,short_window=None)
   joblib.dump(system,R/'models'/f'{name}.joblib',compress=3);cr=e.predict(system,cal);sr=e.predict(system,se);fit_time=time.perf_counter()-tic;cr.to_csv(R/'predictions'/f'calibration_{name}.csv',index=False);sr.to_csv(R/'predictions'/f'selection_{name}_scores.csv',index=False);seen={}
   for target in proto['target_fprs']:
    tt=time.perf_counter();h=threshold(cr.score,target);candidate=f'B_W{w}_q{target:.4f}';r,m=evaluated(sr,h);dupe=seen.get(float(h).hex());seen.setdefault(float(h).hex(),candidate);row=dict(candidate=candidate,experiment='B',system=name,target=target,threshold=h,threshold_delta=h-base['threshold'],complexity=1,status='completed' if active else 'reverted_sparse',duplicate_threshold_of=dupe,fit_system_seconds=fit_time,seconds=time.perf_counter()-tt,calibration_actual_FPR=float((cr.score>h).mean()),calibration_ties=int((cr.score==h).sum()),**m,**paired(br,r))
    for rule,delta in proto['criteria'].items():row.update({rule+'_'+k:v for k,v in compare(bm,m,delta).items()})
    row.update(A_best_candidate=a_best['candidate'],delta_TP_vs_A_best=m['TP']-a_best['TP'],delta_FP_vs_A_best=m['FP']-a_best['FP'],delta_F2_vs_A_best=m['F2']-a_best['F2'],delta_F1_vs_A_best=m['F1']-a_best['F1']);rows.append(row);r['candidate']=candidate;r.to_csv(R/'predictions'/f'selection_{candidate}.csv',index=False)
    for block,idx in blocks.items():
     g=r.loc[idx];b0=br.loc[idx];mm=metrics(g.label,g.score,g.prediction);bb=metrics(b0.label,b0.score,b0.prediction);record=dict(candidate=candidate,stage='selection',block=block,normal=int((g.label==0).sum()),anomaly=int((g.label==1).sum()),normal_bursts=g[g.label==0].burst_id.nunique(),anomaly_bursts=g[g.label==1].burst_id.nunique(),baseline_Recall=bb['Recall'],baseline_FPR=bb['FPR'],baseline_FP=bb['FP'],**mm)
     for rule,delta in proto['criteria'].items():record[rule+'_allowed_extra_FP']=allowed_fp(record['normal'],delta);record[rule+'_FP_limit_met']=mm['FP']<=bb['FP']+record[rule+'_allowed_extra_FP']
     brows.append(record)
  except Exception as exc:
   js(R/'logs'/f'failure_{name}.json',dict(error=repr(exc),traceback=traceback.format_exc()));rows.extend(dict(candidate=f'B_W{w}_q{t:.4f}',experiment='B',system=name,target=t,status='failed',reason=repr(exc),seconds=time.perf_counter()-tic) for t in proto['target_fprs'])
# Append all completed or failed configurations; no hidden exclusions.
allr=pd.concat([A,pd.DataFrame(rows)],ignore_index=True);assert len(allr)<=36;allr.to_csv(R/'all_trials.csv',index=False);pd.concat([pd.read_csv(R/'block_metrics.csv'),pd.DataFrame(brows)]).to_csv(R/'block_metrics.csv',index=False);pd.DataFrame(routeaudit).to_csv(R/'tables/route_calibration_counts.csv',index=False);pd.DataFrame(fitrows).to_csv(R/'manifests/new_model_fit_rows.csv',index=False)
js(R/'checkpoint.json',dict(stage='B_complete',configurations=len(allr),B_wall_seconds=time.monotonic()-start));print(pd.DataFrame(rows)[['candidate','TP','FN','FP','F1','F2','conservative_eligible','primary_eligible','auxiliary_eligible']].to_string(index=False))
