from common import *
import matplotlib.pyplot as plt
from sklearn.metrics import precision_recall_curve
from html import escape

NAME='PCA + R5 예측잔차 보조 경보(G1)'
def table(x,cols=None):
 if cols:x=x[cols]
 return x.to_html(index=False,float_format=lambda n:f'{n:.6f}',na_rep='NA',border=0,escape=True)

def main():
 m=pd.read_csv(R/'metrics.csv');events=pd.read_csv(R/'events.csv');ex=pd.read_csv(R/'normal_exposure.csv');valid=json.loads((R/'validation_report.json').read_text());event=json.loads((R/'event_summary.json').read_text());cal=json.loads((R/'calibration_audit.json').read_text());data=json.loads((R/'data_audit.json').read_text());p=json.loads((R/'validation_protocol.json').read_text());b=pd.read_csv(R/'predictions/H_B0.csv');g=pd.read_csv(R/'predictions/H_G1.csv');he=events[events.block=='H'];err=pd.read_csv(R/'remaining_H_errors.csv');fig=R/'figures';fig.mkdir(exist_ok=True)
 verdict=[]
 for cid in m.model.unique():
  mm=m[m.model==cid].set_index('block');verdict.append(dict(model=cid,S_effect=bool(mm.loc['S','passes']),S1_maintenance=bool(mm.loc['S1','passes']),S2_maintenance=bool(mm.loc['S2','passes']),original_selection_all_conditions=bool(mm.loc[['S','S1','S2'],'passes'].all()),V_stability=bool(mm.loc['V','passes']),V_FN_reduction='not_assessable',H_effect_descriptive=bool(mm.loc['H','passes']),selected_model_unchanged=cid=='G1'))
 verdict=pd.DataFrame(verdict);verdict.to_csv(R/'mandatory_conditions.csv',index=False)
 effects=[]
 for block in ['S1','S2','S','V','H']:
  mm=m[m.block==block].set_index('model')
  for ref,cand,kind in [('R5_A0','B_same_threshold','threshold_only_G0'),('D_old_threshold_G1','G1','threshold_only_G1'),('B_same_threshold','G1','confirmation_only_selected_threshold'),('R5_A0','D_old_threshold_G1','confirmation_only_old_threshold')]:
   effects.append(dict(block=block,comparison=kind,reference=ref,candidate=cand,delta_TP=int(mm.loc[cand,'TP']-mm.loc[ref,'TP']),delta_FN=int(mm.loc[cand,'FN']-mm.loc[ref,'FN']),delta_FP=int(mm.loc[cand,'FP']-mm.loc[ref,'FP']),delta_F1=mm.loc[cand,'F1']-mm.loc[ref,'F1'],delta_F2=mm.loc[cand,'F2']-mm.loc[ref,'F2']))
 effects=pd.DataFrame(effects);effects.to_csv(R/'control_effects.csv',index=False)
 # Curves use predefined continuous scores, never binary alarms as ranking scores.
 plt.figure(figsize=(7,5))
 for cid in ['B0','B_same_threshold','G1','D_old_threshold_G1','R5_A0']:
  f=pd.read_csv(R/f'predictions/H_{cid}.csv');pp,rr,_=precision_recall_curve(f.label,f.integrated_score);plt.plot(rr,pp,label=cid);a=m[(m.block=='H')&(m.model==cid)].iloc[0];plt.scatter(a.Recall,a.Precision,s=30)
 plt.xlabel('Recall');plt.ylabel('Precision');plt.title('Exposed H: fixed score curves and operating points');plt.legend();plt.tight_layout();plt.savefig(fig/'H_PR.png',dpi=150);plt.close()
 f,axs=plt.subplots(1,2,figsize=(10,4))
 for ax,cid in zip(axs,['B0','G1']):
  a=m[(m.block=='H')&(m.model==cid)].iloc[0];cm=np.array([[a.TN,a.FP],[a.FN,a.TP]],int);ax.imshow(cm,cmap='Blues');
  for (i,j),v in np.ndenumerate(cm):ax.text(j,i,str(v),ha='center',va='center',color='red')
  ax.set_xticks([0,1],['pred0','pred1']);ax.set_yticks([0,1],['normal','anomaly']);ax.set_title(cid)
 f.suptitle('Exposed H: row-level confusion matrices');f.tight_layout();f.savefig(fig/'H_confusion.png',dpi=150);plt.close(f)
 f,axs=plt.subplots(1,2,figsize=(11,4))
 for cid in ['B0','G1','B_same_threshold','D_old_threshold_G1','R5_A0']:
  z=m[m.model==cid].set_index('block').loc[['S1','S2','V','H']];axs[0].plot(z.index,z.Recall,'o-',label=cid);axs[1].plot(z.index,z.FPR*100,'o-',label=cid)
 axs[0].set_ylabel('Recall');axs[1].set_ylabel('FPR (%)');axs[1].axhline(1,color='gray',linestyle='--');axs[0].legend(fontsize=7);f.suptitle('Original evaluation blocks; lines connect metrics, not sensor time');f.tight_layout();f.savefig(fig/'time_stability.png',dpi=150);plt.close(f)
 f,axs=plt.subplots(1,2,figsize=(11,4));x=np.arange(len(he));axs[0].bar(x-.18,he.B0_FN,.36,label='B0');axs[0].bar(x+.18,he.G1_FN,.36,label='G1');axs[0].set_xticks(x,he.burst_id,rotation=60);axs[0].set_ylabel('Missed rows per provisional event');axs[0].legend();axs[1].plot(x,he.B0_observed_start_delay_seconds,'o',label='B0');axs[1].plot(x,he.G1_observed_start_delay_seconds,'x',label='G1');axs[1].set_xticks(x,he.burst_id,rotation=60);axs[1].set_ylabel('First alarm - first observed anomaly (s)');axs[1].legend();f.suptitle('Left-censored observation groups: NOT physical failure onset');f.tight_layout();f.savefig(fig/'H_events.png',dpi=150);plt.close(f)
 # Separate each continuity group: no lines across missing acquisition intervals.
 g.TimeStamp=pd.to_datetime(g.TimeStamp);f,axs=plt.subplots(2,1,figsize=(12,6))
 for ax,label in zip(axs,[0,1]):
  z=g[g.label==label]
  for _,v in z.groupby('burst_id',sort=False):ax.plot(v.TimeStamp,v.integrated_score,linewidth=.6,color='steelblue')
  v=z[z.error.isin(['FN','FP'])];ax.scatter(v.TimeStamp,v.integrated_score,c='red',s=14,label='FN / FP');ax.axhline(1,color='black',linestyle='--');ax.set_yscale('symlog',linthresh=1);ax.set_title('Normal date' if label==0 else 'Anomaly date');ax.legend()
 f.suptitle('H error positions; acquisition gaps are disconnected');f.autofmt_xdate();f.tight_layout();f.savefig(fig/'H_errors_time.png',dpi=150);plt.close(f)
 # Fixed past19/future2 context around errors; future shown only, never input.
 context=[];raw=loadrows(R/'inputs/frozen_rows.csv');lookup={v:i for i,v in enumerate(raw.row_id)};outdir=fig/'error_context';outdir.mkdir(exist_ok=True)
 for row in err.itertuples():
  i=lookup[row.row_id];pp=raw[(raw.source_file==row.source_file)&(raw.split=='test')];ii=pp.index.to_numpy();pos=np.flatnonzero(ii==i)[0];vv=raw.loc[ii[max(0,pos-19):pos+3]].copy();vv['focus_row']=row.row_id;vv['relative_observation']=np.arange(max(0,pos-19)-pos,min(len(ii),pos+3)-pos);context.append(vv)
  f,axs=plt.subplots(3,1,figsize=(8,5),sharex=True)
  for ax,sensor in zip(axs,SENSORS):
   for _,gg in vv.groupby('burst_id',sort=False):ax.plot(gg.TimeStamp,gg[sensor],'.-')
   ax.axvline(pd.Timestamp(row.TimeStamp),color='red');ax.set_ylabel(sensor,fontsize=8)
  f.suptitle(f'{row.row_id} {row.error}: past19 / future2 (display only)');f.autofmt_xdate();f.tight_layout();f.savefig(outdir/(row.row_id.replace(':','_')+'.png'),dpi=120);plt.close(f)
 pd.concat(context).to_csv(R/'error_context_rows.csv',index=False)
 # Machine-readable analysis; no parameter changes follow these findings.
 fn=err[err.error=='FN'];causes=dict(R5_unavailable=int(fn.R5_score.isna().sum()),current_above_threshold_but_previous_not=int((fn.h&~fn.h_previous1).sum()),current_not_above_threshold=int((~fn.h&fn.R5_score.notna()).sum()),within_first19_observations=int((fn.burst_pos<=19).sum()))
 js(R/'error_analysis.json',dict(FN_categories=causes,FP_rows=err[err.error=='FP'].row_id.tolist(),physical_cause='unproven: observational score/position categories only',no_retuning=True))
 # Compact Korean report with links to exact CSV evidence and protocol.
 core=m[m.model.isin(['B0','G1'])];hm=m[m.block=='H'];sm=m[m.block=='S'];exh=ex[(ex.block=='H')&ex.model.isin(['B0','G1'])]
 sections=[]
 def sec(title,body):sections.append('<section><h2>'+title+'</h2>'+body+'</section>')
 sec('결론',f'<p><strong>{NAME}</strong>의 고정 추론을 재현했다. H 정상3990·이상357행에서 B0의 TP329/FN28/FP1/TN3989가 G1의 TP344/FN13/FP1/TN3989로 바뀐다. 기존 탐지329행을 모두 보존하고 15행을 추가 탐지했다. S의 엄격 효과 조건과 S1/S2/V 유지 조건도 충족한다. V의 FN0→0은 유지 통과이며 FN 감소 재현은 <code>not_assessable</code>이다.</p><p>새로 발견한 임시 사건은 <strong>0개</strong>다. 13개 관측 이상 구간은 B0도 모두 한 번 이상 탐지했다. 3개 구간에서 탐지 행이 7·1·7개 늘었다. <strong>독립 새 자료 검증은 미실시</strong>이며 현장 개선 입증이 아니다. 이번에는 재학습·후보 선택·배포를 하지 않았다.</p>'+table(core,['block','model','normal_n','anomaly_n','TP','FN','FP','TN','Precision','Recall','FPR','F1','F2']))
 sec('정확히 동결한 모델과 실시간 의미','<p>B0는 P1 창20, PCA2, 15개 mean/std(ddof0)/RMS/min/max 특징, StandardScaler, Q 잔차다. 특징 순서는 통계 종류→AI0/AI1/AI2 순서다. 같은 원 분할 안에서는 시간 공백을 넘어 창을 잇고, 최초19행은 P0를 쓴다. 경보 임계값은 <code>1.3078792257682357</code>; 점수는 각 모델 Q/정상cal Q95 배율이다. P1 Q95=14.9874861938813, P0 Q95=2.649158116699839. 원 PCA 경보에 후처리는 없다.</p><p>R5는 직전 두 센서 벡터(t−1,t−2)로 현재 t를 예측하는 ridge 잔차의 수축 공분산 거리다. 예측은 t−1 관측 후 가능하지만 잔차 경보는 <strong>현재 t의 센서가 도착한 뒤</strong>에만 가능하다. 미래 두 시점을 참조하지 않는다. G1은 현재와 직전 R5 점수가 모두 <code>17.54312199063481</code>을 <strong>strict &gt;</strong> 초과할 때만 보조 경보를 추가한다. 원 경보 OR 보조 경보이며 소급·삭제·연장은 없다.</p><p>R5의 lag와 확인 상태는 파일/원 분할/관측 공백&gt;0.5초에서 초기화한다. 보고용 S1/S2/V 경계에서 P1을 임의 초기화하지 않는다. 실제 설비 운전 세션 ID가 없으므로 버스트는 관측 연속성 대용값이다. G1의 최대 보조 의존 범위는 t−3…t; R5 최초2행은 unavailable, G1 최초 가능 시점은4번째 관측이다. 실제 계산 지연은 측정된 로컬 평균과 별도로 기록하며 타임스탬프를 과거로 옮기지 않는다.</p><p>고정 파일: <a href="model_manifest.json">model_manifest.json</a>, <a href="validation_protocol.json">validation_protocol.json</a>, <a href="row_timing_and_residuals.csv">행별 입력·목표·최초 경보 가능 시각</a>.</p>')
 sec('학습·보정·누출 및 과거 노출 감사',f'<p>원 CSV 정상20000행에서 번호만 다른 추가중복1행을 제외한19999행과 이상600행을 원래 행 ID로 대조했다. 누락·센서 변환 실패는 없다. 모든 비중복 원행은 기존 분할에 배정되어 미사용 원본 시간 구간은 없다. 정상은2022-07-12, 이상은2022-07-17로 날짜와 상태가 겹친다. 단위·설비 ID·실제 고장 시작·운전 세션은 문서화되지 않았다.</p><p>PCA 저장 scaler의 평균/분산 및 PCA 고유쌍이 정상 T에서 계산한 통계와 일치했다. 모델을 재fit하지 않았다. R5 정상T 재학습 일치 검사는 동일 해시의 직전151개 검증 결과를 재사용했다. 현재 추가 검증은 별도 <a href="validation_report.json">검증 기록</a>에 있다. T/C/selection/H 원 분할을 넘는 원자료 창 공유·미래 참조는 발견되지 않았다. P1의 S→V 과거 원자료 사용은 연속 운전의 인과적 입력이며, 보고 경계의 독립성을 뜻하지 않는다. 기존 <a href="inputs/previous/dependency_audit.csv">원자료 의존 감사</a>를 보존했다.</p><p>C 정상 {cal["total_normal"]}행 중 R5 유효 {cal["available"]}행(시작부122행 unavailable)에 higher 방식99.9백분위수를 적용했다. 정렬0기반 순위{cal["rank_zero_based"]}, 동점{cal["ties"]}행, 초과{cal["strict_exceedances"]}행이다. 분위수 해상도는 유효표본 기준 약{100/cal["available"]:.4f}%p이다. 선택/V/H를 calibration에 넣지 않았다. 기존 R5_A0의 정확한 임계값은19.48692067098804이다.</p><p>S는 반복 개발에 노출됐다. 이전 문헌 실험에서는 V 기준선이 공개됐고 R5 V는 미평가였다. 직전 v2에서는 G1 선택 후 V/H를 평가했다고 코드·연결 해시·로컬 파일 시각이 일관되게 기록돼 있다. 그러나 평가 JSON 자체에 독립 시각 인증은 없으며 현재 해시로 과거 사전 고정을 증명할 수 없다. H는 원 PCA부터 반복 공개된 과거 평가다. 이번 대조군 S/V/H 분석도 <strong>사후 분석</strong>이다. <a href="chronology_evidence.json">시각 근거와 한계</a>.</p>')
 sec('임계값과 연속 확인의 효과 분리','<p>B_same_threshold는 선정 임계값을 쓰되 G0, D_old_threshold_G1은 이전 임계값에 G1, R5_A0는 이전 임계값의 G0다. G1은 바꾸지 않는다. B_same_threshold는 이전 R5_A1과 같은 고정 점수/임계값 구성이고, 이전 S 예측과 일치함을 확인했다. 서로 다른 임계값이 S에서는 같은 이진 판정을 만들지만 H에서는 달라진다.</p>'+table(hm,['model','TP','FN','FP','F1','F2','FPR'])+'<p>H에서 G0의 임계값을19.4869→17.5431로 낮추면 TP+1·FP+1이다. G1 확인을 유지한 같은 임계값 완화는 TP+2·FP+0이다. 선정 임계값에서 G0→G1은 TP3개를 잃는 대신 FP3개를 제거한다. S에서는 TP1개를 잃는 대신 S2의 FP1개를 제거한다. 그래서 연속 확인에는 짧고 고립된 이상의 미탐 대가가 있다. B0 탐지는 어느 대조군에서도 사라지지 않았다.</p>'+table(effects[effects.block.isin(['S','H'])])+'<p>G0는 pooled S 기준만 보면 좋아도 S2 FP6→7 때문에 추가 FP 허용0개와 절대 FPR1%를 모두 위반한다. pooled와 필수 블록을 혼동하지 않는다. H 점수가 더 높은 G0로 재선정하지 않는다.</p>'+table(verdict)+'<p>전체 수치: <a href="metrics.csv">metrics.csv</a>, <a href="paired_changes.csv">기준별 원행 변화</a>. AP/사다리꼴PR-AUC/ROC-AUC도 metrics.csv에 구분했다. 연속 통합 점수는 G1에서 max(B0_score/B0_threshold, min(s_t/θ,s_t−1/θ)), unavailable=0이며 &gt;1과 이진 경보가 같다. 확률이 아니다. 모든 PR 곡선은 같은 H행의 연속 점수로 계산했다.</p><img src="figures/H_PR.png"><img src="figures/H_confusion.png">')
 sec('사건 단위 효과와 지연','<p>물리 사건 ID가 없으므로 같은 파일·원 분할·시간 공백0.5초 이하 관측 구간 안의 연속 이상 라벨을 임시 사건으로 고정했다. 긴 공백에서 끊으며 결과를 보고 합치지 않았다. 13개 모두 관측 시작부터 이상이므로 실제 고장 시작은 좌측 검열 상태다. 한 점 경보로 나머지 행을 정탐으로 바꾸지 않았다.</p>'+table(he,['burst_id','rows','B0_TP','B0_FN','G1_TP','G1_FN','added_detected_rows','B0_observed_start_delay_seconds','G1_observed_start_delay_seconds'])+'<p>1:9 구간에서 첫 경보는 관측 시작+0.4초→+0.3초, 즉0.1초 빨라졌다. 나머지12개는 최초 관측 시점 경보가 같았다. 이는 <strong>고장 전 조기예측 시간도 실제 고장 탐지 지연도 아니다</strong>. H에서 무경보 임시 사건은 양쪽0개다. 일반 코드에서 미탐 사건 지연은NA로 남긴다.</p><img src="figures/H_events.png"><p><a href="events.csv">모든 블록 사건표</a> · <a href="event_row_predictions.csv">사건별 원행 예측</a></p>')
 sec('오경보 노출시간과 남은 오류',table(exh)+'<p>H의 정상 관측 시간 합은387.2초다. 같은 관측 구간의 연속 정상 타임스탬프 차이만 더하고 공백·끝점 외삽은 제외했다. B0/G1의 FP1행은 오경보 episode1개이며, 해당 관측시간으로 환산하면9.2975회/시간이다. 짧은 기록의 환산값이고 실제 정상 가동시간이나 현장 시간당 오경보율이 확인된 것은 아니다. 정상1000행당 FP는0.250627개다.</p>'+f'<p>남은 FN13행 중 시작부 R5 unavailable {causes["R5_unavailable"]}행, 현재 초과하지만 직전 비초과 {causes["current_above_threshold_but_previous_not"]}행, 현재 비초과 {causes["current_not_above_threshold"]}행이다. 첫19관측 안에 {causes["within_first19_observations"]}행이 있다. 센서나 부하의 물리적 고장 원인으로 확정하지 않는다. FP행0:19019는 원 PCA 점수1.415328이 원 임계값1.307879를 초과한 경우이고 R5는7.403458로 보조 경보를 만들지 않았다. OR 구조로 원 FP를 제거할 수 없다.</p>'+table(err,['row_id','error','burst_id','burst_pos','score','R5_score','h','h_previous1','AI0_Vibration','AI1_Vibration','AI2_Current'])+'<p>오류 주변은 사전 고정한 과거19행/미래2행으로 표시했다. 미래2행은 진단 그림 전용이며 입력에 들어가지 않는다. <a href="error_context_rows.csv">주변 원행</a>, <a href="figures/error_context/0_19019.png">FP 주변 그림</a>.</p><img src="figures/H_errors_time.png">')
 sec('시간 안정성과 검증에서 드러난 한계','<p>필수 블록의 추가 FP 상한은 floor(0.001×정상행수), 절대 상한은 floor(0.01×정상행수)다. S1/S2/V 추가 허용은 각각0개, pooled S1개, H3개다. 모두 반올림 전값·1e−12 허용오차를 사용했다. 정상만 있는 설명용 구간은 FP/FPR를 보며 F1/F2/Recall은NA다. 추가 설명용 날짜/버스트에 사후 탈락기준을 만들지 않았다.</p><p>한 날짜씩 클래스가 분리돼 있고 독립 설비 세션을 알 수 없어 iid bootstrap·유의확률·일반화 신뢰구간을 제시하지 않았다. 버스트13개는 독립 고장13건이 아니다. <a href="temporal_descriptive.csv">날짜/관측 구간별 설명표</a>.</p><p>원 모델·원행·기존 예측·ZIP의 해시와 판정을 검증했고 기존151개 검증은 같은 해시인 범위에서 재사용했다. 이번에는 새 고정 대조군의 온라인/batch 비교와 별도 프로세스 모델 재로딩·새 입력 도구를 검증했다. 미래 값 변경 시 과거 결과 불변 검사는 동일 코드의 기존 결과를 재사용했다. 실험용 S 배열을 처음 합칠 때 순서가 달라진 출력 조립 오류는 원행 정렬 검사에서 중단됐고, 시간순 정렬을 복원했다. 모델·점수·선택은 바꾸지 않았으며 실패 로그를 보존했다.</p><p>추가로 확인한 실제 입력 계약 결함: 원 온라인 helper는 NaN PCA 점수를 strict 비교하면 정상(False)처럼 반환할 수 있다. 원 데이터는 완전해서 현재 성능 재현에는 영향이 없다. 외부 자료용 래퍼에서 결측/무한대 센서를 거부하도록 최소 보완했다. 잘못된 행을 지우거나 정상으로 세지 않는다. 원 모델·추론 helper는 보존했다. <a href="missing_input_contract.json">결함 재현과 보완 범위</a>.</p><img src="figures/time_stability.png">')
 sec('독립 새 자료와 재실행','<p>현재 프로젝트의 원 데이터·분할·보고 자료와 제공 패키지에서 별도 수집 세션을 찾지 못했다. 복사와 재분할은 새 자료로 보지 않는다. 다른 에이전트의 새 작업 폴더나 접근 불가 외부 자료는 조사 범위가 아니다. 독립 새 자료 검증은 <strong>미실시</strong>다. <a href="new_data_inventory.json">조사 범위·해시</a>.</p><p>새 자료용 <a href="src/evaluate_new_data.py">evaluate_new_data.py</a>는 B0/G1만 고정 추론하며 예측 CSV와SHA를 먼저 저장한 뒤 별도 라벨 파일을 연다. 원 입력 단위가 미확인이라 센서 의미·단위 호환성을 제공자가 확인해야 한다. 파일명/세션/날짜는 경계·추적용이며 모델 입력은 센서3개뿐이다. 외부 스크립트의 이번 시험은 <strong>기존 H를 재생한 API 검증</strong>이고 새 자료 성능이 아니다. 합성 결측 입력도 계약 시험 전용이다.</p><p><a href="README_ko.md">입력 스키마·실행 예시</a> · <a href="RUN_REVIEW.sh">RUN_REVIEW.sh</a> · <a href="portable_replay.json">독립 경로 재실행 기록</a> · <a href="package_integrity.json">패키지 무결성 기록</a></p><pre>bash RUN_REVIEW.sh /새로운/출력폴더</pre><p>Python3.14와 requirements.lock.txt를 사용한다. 원 작업 폴더 없이 압축 안 모델·데이터·소스만으로 실행한다. 환경 생성 및 패키지 설치는 네트워크 가용성에 달려 있다. 학습은 재실행하지 않고 고정 모델 검증을 재현한다.</p>')
 sec('해석 범위와 확인한 문헌','<p>검출기 적합은 정상T 전용이지만 모델/운영 구성 선택에는 과거 개발 이상 라벨을 사용했다. 완전 비지도 전체 절차가 아니다. 반복 사용한 자료의 개선·추론 재현성·사건 내 탐지 범위·독립 새 자료 성능은 서로 다르다. FP 예산·G1·분위수·시간 블록은 프로젝트 설계이며 공식 대회·논문 필수 규칙이 아니다.</p><p><a href="https://jmlr.org/papers/v11/cawley10a.html">Cawley &amp; Talbot (2010), On Over-fitting in Model Selection and Subsequent Selection Bias in Performance Evaluation</a>: 공식 초록을 확인했다. 후보 선택 기준 자체의 과적합과 평가 편향 가능성에 연결한다. DOI는 확인되지 않아 기재하지 않는다.</p><p><a href="https://robjhyndman.com/papers/cv-wp.pdf">Bergmeir, Hyndman &amp; Koo, A Note on the Validity of Cross-Validation for Evaluating Autoregressive Time Series Prediction</a>: 공개 원문 초록·§1–2를 확인했다. 순수 자기회귀 및 비상관 오차 같은 가정을 전제로 한 논의이며 모든 시계열 무작위CV를 금지한 논문으로 인용하지 않는다. 현재 원행 의존성과 날짜 혼재 문제를 이 논문으로 해결했다고 주장하지 않는다.</p>')
 html='<!doctype html><html lang="ko"><meta charset="utf-8"><title>'+NAME+' 고정 검증</title><style>body{font-family:system-ui,sans-serif;max-width:1250px;margin:auto;padding:32px;line-height:1.7;color:#172b3a}h1,h2{color:#17486d}section{margin:36px 0;overflow-x:auto}table{border-collapse:collapse;font-size:13px}td,th{border:1px solid #cdd7df;padding:7px}th{background:#eaf1f7}img{max-width:100%;height:auto}code,pre{background:#edf2f5;padding:3px}a{color:#086fbd}</style><h1>'+NAME+' 고정 검증</h1><p>모델 동결 · 사후 대조 · 관측 사건 분석 · 독립 새 자료 미확보</p>'+''.join(sections)+'</html>'
 (R/'review_report_ko.html').write_text(html)
 md=f'''# {NAME} 고정 검증\n\nH: B0 TP329/FN28/FP1 → G1 TP344/FN13/FP1. F1 0.957787→0.980057, F2 0.935722→0.970107.\n\nS: FN3→2, FP8 유지. V: 양쪽 FN0/FP0, 유지 통과·FN 감소 not_assessable.\n\n추가 탐지15행은 이미 탐지한3개 임시 사건의 범위 확장이다. 새로 발견한 전체 사건0개. 관측 시작 대비 첫 경보는1개 구간에서0.4→0.3초, 나머지 동일. 실제 고장 시작은 미확인.\n\n같은 임계값의 G0는 H FN10/FP4, G1은 FN13/FP1. G0는 S2 FP7로 필수조건 실패. 이전 임계값의 G1은 H FN15/FP1. 선정 모델은 교체하지 않았다.\n\n원행·판정 재현 및 온라인 일치. 미래 참조 없음(동일 버전의 기존 인과성 시험 재사용). 기존151개 검증은 새151개 실험이 아니다. NaN 온라인 입력 계약 결함은 별도 외부 입력 검사로 보완; 완전한 기존 데이터 결과 불변.\n\n독립 새 자료 검증 미실시. 재사용 자료의 개선이고 현장 검증 완료가 아니다. 상세 표·그림·근거·한계는 [한국어 HTML](review_report_ko.html).\n'''
 (R/'review_report_ko.md').write_text(md)
 js(R/'references.json',[dict(title='On Over-fitting in Model Selection and Subsequent Selection Bias in Performance Evaluation',authors='Cawley; Talbot',year=2010,url='https://jmlr.org/papers/v11/cawley10a.html',read='official abstract',doi=None),dict(title='A Note on the Validity of Cross-Validation for Evaluating Autoregressive Time Series Prediction',authors='Bergmeir; Hyndman; Koo',url='https://robjhyndman.com/papers/cv-wp.pdf',read='abstract and sections1-2 of author preprint',application='assumptions matter; not universal random-CV prohibition')])
 print('Korean report and figures complete')
if __name__=='__main__':main()
