from v2 import *
import csv,os,zipfile

def main():
 assert not (R/'validation_protocol.json').exists();d,e,b0,r5=context();old=json.loads((R/'inputs/previous/selected_config.json').read_text());prev=json.loads((R/'inputs/previous/literature_selected_config.json').read_text());theta=old['selected_config']['theta'];oldtheta=prev['configs']['R5_A0']['threshold'];assert theta==17.54312199063481 and oldtheta==19.48692067098804
 models={}
 for w,x in b0['entries'].items():
  bu=x['bundle'];models[str(w)]=dict(feature_order=bu['names'],kept=bu['keep'],scaler_mean=bu['scaler'].mean_,scaler_scale=bu['scaler'].scale_,PCA_components=bu['model'].n_components_,rank=bu['rank'],solver=bu['model'].svd_solver,whiten=bu['model'].whiten,Q95_reference=x['reference'])
 manifest=dict(name='PCA + R5 예측잔차 보조 경보(G1)',baseline_name=b0.get('name'),baseline_output_id='baseline',B0_alias=True,B0_threshold=b0['threshold'],G1_theta=theta,old_R5_A0_theta=oldtheta,quantile=.999,method='higher',operator='strict >',B0=models,R5=dict(lag=2,forecast_horizon='one observation ahead: uses t-1 and t-2 to predict t, not horizon2',ridge_lambda=r5['lambda_'],seed='none: deterministic fitted PCA/ridge; no seed search',raw_scaler_mean=r5['scaler'].mean_,raw_scaler_scale=r5['scaler'].scale_),hashes={f.name:sha(f) for f in (R/'models').glob('*.joblib')},missing='original complete-data validation only; batch B0 asserts finite. Original online helper has no reliable finite B0 score with NaN. New external-input wrapper must reject incomplete sensors, never interpret NaN comparison as normal.',warmup='B0 P0 first19 per original partition; R5 unavailable first2 per gap-observation group; G1 previous h unavailable=0',reset='P1 only source_file/split/train_role; R5 lag2 and h reset additionally gap>.5; report blocks do not reset',physical_session='not recorded; burst is an observation-continuity proxy, not verified operation session')
 js(R/'model_manifest.json',manifest)
 controls=[dict(id='B0',rule='B0',theta=None),dict(id='B_same_threshold',rule='G0',theta=theta),dict(id='G1',rule='G1',theta=theta),dict(id='D_old_threshold_G1',rule='G1',theta=oldtheta),dict(id='R5_A0',rule='G0',theta=oldtheta)]
 p=dict(created=pd.Timestamp.now(tz='UTC').isoformat(),purpose='frozen validation and explicitly post-hoc controls; no reselection or training',model_manifest_sha256=sha(R/'model_manifest.json'),data_sha256=sha(R/'inputs/frozen_rows.csv'),old_selection_sha256=sha(R/'inputs/previous/selected_config.json'),old_protocol_sha256=sha(R/'inputs/previous/protocol_v2.json'),controls=controls,evaluation_order=['verify stored B0/G1 S/V/H rows/scores','recover fit/calibration and exposure history','post-hoc controls on original C and selection full stream and H','derive S1/S2/S/V/H metrics without resetting at report boundaries','event/normal exposure analyses','independent data if verified; otherwise provide evaluator','standalone replay and ZIP integrity'],blocks=json.loads((R/'manifests/blocks.json').read_text()),time_blocks='original S1,S2,V,H only, plus acquisition date and continuity groups descriptive; no new pass/fail blocks',event_definition='No physical event ID found: contiguous label1 run within source_file/original partition and observation group; gap>.5s breaks event; baseline/G1 evaluated on identical events',event_start='label-observed start only; left boundary at first sampled anomaly => physical onset unknown/left-censored',normal_exposure='sum actual adjacent timestamp intervals with both labels0, same source/partition and gap<=.5s; no gap time, no extrapolated endpoint interval, singletons0; FP rows and alarm episodes per observed span hour, not verified machine runtime',FP_delta=.001,FPR_cap=.01,rounding='floor integer, never minimum1',tolerance=1e-12,mandatory={'S1':'maintenance','S2':'maintenance','S':'strict effect','V':'maintenance','H':'strict effect'},judge='reuse frozen v2 judge; no anomaly -> FP only; FNbase0 -> reduction not_assessable; maintenance allows equal FN/F1/F2',new_data='same fixed B0/G1 only; model/schema/units/labels/session provenance must be confirmed; predict and hash before opening labels; no fit',diagnostic_context='past19 rows and future2 rows within original partition; future only displayed',uncertainty='no iid bootstrap; one date per class, no independent equipment sessions; disclose event counts, no p-value or future-generalization CI',prior_exposure='S diagnosed and repeatedly selected; V/H repeatedly observed, original baseline selected earlier on development; v2 G1 locked then V/H tested per local artifacts, not cryptographic timestamp attestation',reuse='reuse prior151 tests where exact source/model/data hashes match; do not repeat normal training',core_sources={f.name:sha(f) for f in (R/'src').glob('*.py')})
 js(R/'validation_protocol.json',p);(R/'validation_protocol.sha256').write_text(sha(R/'validation_protocol.json')+'\n')
 print('Protocol frozen with five configurations; selected G1 unchanged')
if __name__=='__main__':main()
