from core import *
R=Path(__file__).resolve().parents[1]
base=dict(mode='unaware',feat='full',scaler='standard',k=2,kind='PCA',score='Q',align='q95')
def s(name,**kw):return dict(base,id=name,**kw) if not set(kw)&set(base) else base|dict(id=name)|kw
specs=[s('P1_Q'),s('P1_T2',score='T2'),s('P1_QT',score='QT'),s('P2_Q',mode='aware'),s('ROUTE_Q',mode='route'),s('CAP25_Q',mode='cap'),s('ROBUST_Q',scaler='robust'),s('COMPACT_Q',feat='compact'),s('MEANSTD_Q',feat='meanstd'),s('MEDIANIQR_Q',feat='medianiqr'),s('DELTA_Q',mode='aware',feat='delta'),s('ROUTE_ECDF_Q',mode='route',align='ecdf'),s('P1_ECDF_Q',align='ecdf'),s('P0_Q',mode='raw'),s('IF_P1',kind='IF',score='IF'),s('IF_P2',kind='IF',score='IF',mode='aware'),s('P1_K3_Q',k=3),s('P1_K5_Q',k=5)]
protocol=dict(created=pd.Timestamp.now(tz='UTC').isoformat(),candidate_specs=specs,targets=[.001,.005,.01],candidate_count=54,postprocessing_reserved=2,max_new_operating_configurations=56,train_wall_seconds_budget=7200,threads=2,seeds=[42,43,44],confirmation_seeds=[45,46],primary_selection='PCA only; pooled inner FPR<=.01; Recall desc, F2 desc, F1 desc, AP desc; candidate ID then smaller target deterministic tie-break. Each-block FPR and minimum recall reported, pooled constraint not silently strengthened.',selection_blocks=['inner_early','inner_late'],outer_holdout='outer_development, not used for selection; same exposed development data, not independent test',historical='already exposed historical evaluation, final selected systems only; no tuning',fit='original normal train, preserved train_role boundary; same model reused across temporal calibration blocks',fallback='same standard-scaled raw k2 Q for all PCA; seed-matched I0 for IF; scored separately',routing=dict(lengths=[1,3,5,10,20],causal='largest available length within current burst',min_train=100,min_routed_normal_calibration=50,sparse_rule='use all available normal calibration windows of same route model; if total <50 exclude system',calibration='normal-only per-route Q95; full operating system quantile recalibration'),ecdf='(right searchsorted rank + .5)/(n+1); ties equal; no tail extrapolation; scores saturate; not probability',threshold=dict(quantile='higher',rule='>',ties='normal',no_label_use=True),feature_boundary='review_partition + source_file + train_role; aware additionally burst; calibration split into early/late to ensure no raw sharing with inner_early evaluation',policy_boundary='file, partition and burst; unique burst IDs within each evaluated partition',max_gap=.5,time_cap=2.5,constant_rule='std <= 1e-12*max(1,abs(mean))',eigen_tolerance='max(1e-12,lambda_max*1e-10)',q_valid='k<effective_rank',postprocess=['consecutive2','two_of_three'],postprocess_selection='separate descriptive experiment on selected system at selected target; never replace primary',mode_pca='not run: no recorded operating mode; focus budget A-E, avoid additional exploratory clustering with few anomaly bursts',source_hashes={p.name:sha(p) for p in (R/'src').glob('*.py')})
js(R/'protocol.json',protocol)
(R/'hypotheses.md').write_text('''# 사전 가설과 반증 조건\n\n기존 과거 평가 결과와 오류는 이미 알려져 있다. 특히 첫19행 FN 집중이 H2의 착안이며 신규 선택에는 과거 평가를 사용하지 않는다. 아래 기준은 프로젝트 자체 설계다.\n\n1. H1 알고리즘 효과: 동일15특징·창20·정상 fit행·scaler·보정·공통행에서 PCA Q와 IF를 비교한다. 전체 운영은 각자 fallback이므로 별도다. 동일조건에서 이득이 사라지면 알고리즘 우위 주장을 기각한다. 원모델의 임계값만 변경한 세 운영점도 포함한다.\n2. H2 시작부 병목: 단일 P0와 버스트 인과적1→3→5→10→20 라우팅. normal cal route≥50, fit≥100을 사전 규정하고 sparse route는 동일 길이 전체 cal로 되돌린다. 개발에서 FN 감소 없이 FP만 늘면 기각한다. 미래 burst_length는 분석에만 사용한다.\n3. H3 시간 혼합: P1/P2 동일조건과 P1 실제 경과시간≤2.5초 cap/P0를 비교한다. 전체와 공통행을 분리하고 native coverage 개선으로 해석하지 않는다. common-fit/common-cal 대조에서 일치 여부도 검증한다.\n4. H4 특징 중복: RMS²=mean²+std²의 수치 잔차와 표준화 특징 조건수를 정상 학습에서 진단한다. full/compact/meanstd/medianIQR와 Standard/Robust를 한 요소씩 비교한다. delta는 버스트 내부에서만 계산하므로 P2를 대조군으로 사용한다. 성능 이득이 없으면 불필요한 특징 변경을 기각한다.\n5. H5 점수 결합/정렬: Q/T²/max 재보정과 개별 OR를 구별한다. Q95 대 ECDF 비교, 표본 해상도와 꼬리 동점을 보고한다. Recall 이득이 FP 증가만으로 얻어지면 교환관계로 기록한다.\n\n18기본구성×3목표FPR=54개, 최종 PCA 후처리2개=56개 이내. IF seed/fold는 반복이지 추가구성 아님. PCA seed 반복은 없음. 모드별 PCA는 추가하지 않는다. 모델 선택은 두 내부 시간블록 pooled FPR≤1%, Recall→F2→F1→AP. 각블록 준수/최저Recall 별도. 개발 후반을 외부점검으로 남기되 새로운 독립 자료로 부르지 않는다.\n''')
rows=[
('대표329/28/1/3989','PDF 표2; reproduction.json','src/infer.py; src/reproduce.py','적절히 처리됨','저장추론과 재학습 재현','행ID·연속점수·판정 대조','A'),
('정상만 fit, 누출 없음','PDF 자료/분할; frozen rows','core.py:Engine.model/window','미검증 가설','이상적 성능의 누출 가능성','fit행과 원시창 경계·미래변경 시험','A'),
('PCA>IF 알고리즘','PDF 표2 창20 IF 존재','core.py; controlled_comparison.csv','한계','전체 운영에는 fallback/보정의 효과 포함','동일fit/cal/common rows 비교','A'),
('첫19행 FN26','PDF 오류분석 문단','reproduce.py','미검증 가설','시작부 routing 이득 가능','개발에서도 원인조건 조사 후 H2','B'),
('Q와 T² 수학/유효rank','PDF 점수 절; 원models.py','models.py:fit_pca/score','적절히 처리됨','전체차원 Q/0고유값 의심','독립 공식 수치 대조, rank 확인','A'),
('버스트 처리 우위','PDF 동일행/운영 표','core.py:window/routes','한계','학습수·coverage·보정분포 바뀜','common train/cal 대응 및 P1/P2','A'),
('95백분위수 배율','PDF 결합과 운영','core.py:fit_system','한계','route tail FPR는 균등 보장 안 됨','라우트분모/오류와 ECDF 꼬리 진단','B'),
('독립 날짜 일반화','PDF 제한점','data_audit.json','한계','날짜와 라벨 교락','새 날짜·설비 없이는 해결 불가','A'),
('실제 고장 조기탐지','PDF 조기탐지 절','evaluation.py:alarm_summary','적절히 처리됨','시작 정답 없어 계산 불가','관측시작→경보만 계산','A'),
('후처리로 개선','PDF 후처리 표','evaluation.py:postprocess','한계','FP줄어도 FN증가 가능','raw/2연속/2of3 비용 동시 보고','B'),
('특징 중복·불안정','PDF15특징','core.py:stat_features/model','미검증 가설','비선형중복은 선형rank결함과 다름','관계식 잔차·조건수·축소 대조','B'),
('독립 신뢰구간/유의성','PDF 제한점','report.py','적절히 처리됨','행종속·소수버스트','유의성 주장 없음; seed변동 구분','B')]
pd.DataFrame(rows,columns=['claim','paper_evidence','code_evidence','status','expected_impact','falsification','priority']).to_csv(R/'critique_matrix.csv',index=False)
print('Protocol frozen:',len(specs),'specs, 56 max operating configurations')
